apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-pytorch-pvc-job
  labels:
    app: mnist-pytorch-pvc-job
spec:
  completions: 3
  parallelism: 3
  completionMode: Indexed
  backoffLimit: 4
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: mnist-pytorch-pvc-job
    spec:
      containers:
      - name: mnist-pytorch
        image: gitlab-registry.nrp-nautilus.io/ndp/schmidt-ai/mnist-pytorch:latest
        command: ["bash", "-c", "\
          params=( \
            \"--lr 0.01 --gamma 0.7 --batch-size 64\" \
            \"--lr 0.001 --gamma 0.7 --batch-size 128\" \
            \"--lr 0.0001 --gamma 0.7 --batch-size 256\" ); \
          idx=$JOB_COMPLETION_INDEX; \
          echo \"Running experiment: ${params[$idx]}\"; \
          python main.py ${params[$idx]}"]
        resources:
          limits:
            cpu: 4
            memory: 10Gi
            nvidia.com/gpu: 1
          requests:
            cpu: 4
            memory: 10Gi
            nvidia.com/gpu: 1
        envFrom:
        - secretRef:
            name: mnist-pytorch
        volumeMounts:
        - mountPath: /data/
          name: mnist-pytorch-pvc
      restartPolicy: Never
      volumes:
      - name: mnist-pytorch-pvc
        persistentVolumeClaim:
          claimName: mnist-pytorch-pvc
