apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-pytorch-pelican-job
  labels:
    app: mnist-pytorch-pelican-job
spec:
  completions: 3
  parallelism: 3
  completionMode: Indexed
  backoffLimit: 4
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: mnist-pytorch-pelican-job
    spec:
      containers:
      - name: mnist-pytorch
        image: gitlab-registry.nrp-nautilus.io/ndp/schmidt-ai/mnist-pytorch:latest
        command: ["bash", "-c", "\
          params=( \
            \"--lr 0.01 --gamma 0.7 --batch-size 64 --data-protocol pelican\" \
            \"--lr 0.001 --gamma 0.7 --batch-size 128 --data-protocol pelican\" \
            \"--lr 0.0001 --gamma 0.7 --batch-size 256 --data-protocol pelican\" ); \
          idx=$JOB_COMPLETION_INDEX; \
          echo \"Running experiment: ${params[$idx]}\"; \
          python main.py ${params[$idx]}"]
        resources:
          limits:
            cpu: 4
            memory: 10Gi
            nvidia.com/gpu: 1
            ephemeral-storage: 50Gi
          requests:
            cpu: 4
            memory: 10Gi
            nvidia.com/gpu: 1
            ephemeral-storage: 50Gi
        envFrom:
        - secretRef:
            name: mnist-pytorch
      restartPolicy: Never
