apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mnist-pytorch-pvc
spec:
  storageClassName: rook-cephfs
  accessModes:
    -  ReadWriteMany
  resources:
    requests:
      storage: 100Gi