name: Push to NRP GitLab Registry

on:
  push:
    branches:
      - main  # Change as needed
    tags:
      - 'v*'  # Supports semantic versioning tags (v1.0.0, v2.1.3, etc.)

jobs:
  push-to-gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Image Tag
        id: vars
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          TAG_NAME=${GITHUB_REF#refs/tags/}

          if [[ "$GITHUB_REF" == refs/heads/* ]]; then
            IMAGE_TAG=${BRANCH_NAME}
          elif [[ "$GITHUB_REF" == refs/tags/* ]]; then
            IMAGE_TAG=${TAG_NAME}
          else
            IMAGE_TAG="latest"
          fi

          IMAGE_TAG=$(echo "$IMAGE_TAG" | tr '/' '-')  # Replace slashes with dashes for branch names
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Log in to NRP GitLab Container Registry
        run: echo "${{ secrets.NRP_GITLAB_PAT }}" | docker login ${{ secrets.NRP_GITLAB_REGISTRY_URL }} -u ${{ secrets.NRP_GITLAB_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.NRP_GITLAB_REGISTRY_URL }}/ndp/schmidt-ai/mnist-pytorch:${{ env.IMAGE_TAG }} mnist-pytorch
          docker tag ${{ secrets.NRP_GITLAB_REGISTRY_URL }}/ndp/schmidt-ai/mnist-pytorch:${{ env.IMAGE_TAG }} ${{ secrets.NRP_GITLAB_REGISTRY_URL }}/ndp/schmidt-ai/mnist-pytorch:latest

      - name: Push Docker Image to GitLab Registry
        run: |
          docker push ${{ secrets.NRP_GITLAB_REGISTRY_URL }}/ndp/schmidt-ai/mnist-pytorch:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.NRP_GITLAB_REGISTRY_URL }}/ndp/schmidt-ai/mnist-pytorch:latest

